#ifndef JUSTOLIUNET_HPP
#define JUSTOLIUNET_HPP

// Sea/land/cloud classification of one HYPSO-2 pixel from its raw L1a
// spectrum, as trained in hypso-onboard-segmentation:
//
//   spectrum [RAW_BANDS]  raw L1a
//   preprocess: keep BANDS bands, z-score each with the training statistics
//   1D-Justo-LiuNet (Justo et al., arXiv:2310.16210):
//     4 x [ Conv1D kernel K, valid -> ReLU -> MaxPool 2 ]
//     flatten (channel-major, as PyTorch) -> Dense -> logits [CLASSES]
//   classes: 0 cloud, 1 land, 2 sea
//
// Band selection, statistics and weights come from justoliunet_weights.hpp,
// generated by tools/export_justoliunet.py. float32 throughout, so results
// match the trained model; fixed point is the next optimization.

#include "justoliunet_weights.hpp"

namespace jl {
constexpr int L1 = (BANDS - K + 1) / 2;  // length after each conv + pool
constexpr int L2 = (L1 - K + 1) / 2;
constexpr int L3 = (L2 - K + 1) / 2;
constexpr int L4 = (L3 - K + 1) / 2;
constexpr int FEATURES = C4 * L4;
static_assert(L4 >= 1, "spectrum too short for four conv + pool stages");
}

void justoliunet(const float spectrum[jl::RAW_BANDS], float logits[jl::CLASSES]);

#endif
