#!/usr/bin/env python3
"""Export a 1D-Justo-LiuNet checkpoint to the justoliunet HLS kernel (needs numpy).

1D-Justo-LiuNet (Justo et al., arXiv:2310.16210) classifies one pixel from its
spectrum: 4 x [Conv1D k=6 valid -> ReLU -> MaxPool 2], flatten, Dense -> logits.
Writes, from one checkpoint:

  src/hls/justoliunet/justoliunet_weights.hpp   weights and layer sizes (float)
  tb/justoliunet/justoliunet_vectors.hpp        test inputs + expected logits
  tb/data/justoliunet_vectors.txt               the same vectors, for the board

Expected logits come from the numpy forward pass below, not from PyTorch.
A BatchNorm directly after a conv (justoliunet_bn) is folded into that conv.

    python tools/export_justoliunet.py [checkpoint.pt]
"""
import argparse
import re
from pathlib import Path

import numpy as np

import pt_reader

ROOT = Path(__file__).resolve().parents[1]
DEFAULT = 'weights/fp32/justoliunet/justoliunet_pixel1d_e31_miou0-908_K110.pt'
BN_EPS = 1e-5  # PyTorch BatchNorm default
MIN_MARGIN = 0.05  # keep test pixels whose top two logits differ at least this much


def load_layers(path):
    sd = pt_reader.state_dict(path)
    convs = []
    for i in range(1, 5):
        w = sd[f'conv{i}.weight'].astype(np.float64)
        b = sd[f'conv{i}.bias'].astype(np.float64)
        if f'bn{i}.weight' in sd:
            scale = sd[f'bn{i}.weight'] / np.sqrt(sd[f'bn{i}.running_var'] + BN_EPS)
            w = w * scale[:, None, None]
            b = (b - sd[f'bn{i}.running_mean']) * scale + sd[f'bn{i}.bias']
        convs.append((w, b))
    fc = (sd['fc.weight'].astype(np.float64), sd['fc.bias'].astype(np.float64))
    return convs, fc


def check_sizes(convs, fc, bands):
    k = convs[0][0].shape[2]
    if convs[0][0].shape[1] != 1 or any(w.shape[2] != k for w, _ in convs):
        raise SystemExit('expected one input channel and the same kernel size in every conv')
    length = bands
    for _ in convs:
        length = (length - k + 1) // 2
    if length * convs[-1][0].shape[0] != fc[0].shape[1]:
        raise SystemExit(f'{bands} bands give {length * convs[-1][0].shape[0]} dense inputs, '
                         f'checkpoint has {fc[0].shape[1]}; pass --bands')
    return k


def bands_from_name(path):
    # Training runs are named ..._K110.pt (pixel1d) or ..._C110_P32.pt (patch2d).
    match = re.search(r'_[KC](\d+)(?:_|\.pt$)', Path(path).name)
    return int(match.group(1)) if match else None


def forward(convs, fc, spectra):
    """Logits for spectra of shape (pixels, bands), in float64."""
    h = spectra[:, None, :]
    for w, b in convs:
        k = w.shape[2]
        length = h.shape[2] - k + 1
        windows = np.stack([h[:, :, j:j + length] for j in range(k)], axis=-1)
        conv = np.einsum('nilk,oik->nol', windows, w) + b[None, :, None]
        conv = np.maximum(conv, 0.0)
        half = length // 2
        h = conv[:, :, :2 * half].reshape(conv.shape[0], conv.shape[1], half, 2).max(axis=3)
    features = h.reshape(h.shape[0], -1)  # PyTorch flatten: channel-major
    return features @ fc[0].T + fc[1]


def synthetic_spectra(rng, count, bands):
    """Smooth random curves, min-max normalized per pixel like the training data."""
    x = np.linspace(0.0, 1.0, bands)
    curves = np.cumsum(rng.normal(0.0, 1.0, (count, bands)), axis=1)
    for _ in range(3):
        centre = rng.uniform(0, 1, (count, 1))
        width = rng.uniform(0.03, 0.3, (count, 1))
        height = rng.normal(0, 8, (count, 1))
        curves += height * np.exp(-((x - centre) / width) ** 2)
    lo, hi = curves.min(axis=1, keepdims=True), curves.max(axis=1, keepdims=True)
    return ((curves - lo) / (hi - lo)).astype(np.float32).astype(np.float64)


def pick_vectors(convs, fc, bands, per_class, seed):
    rng = np.random.default_rng(seed)
    pool = synthetic_spectra(rng, 20000, bands)
    logits = forward(convs, fc, pool)
    ranked = np.sort(logits, axis=1)
    clear = ranked[:, -1] - ranked[:, -2] >= MIN_MARGIN
    chosen = []
    for cls in range(logits.shape[1]):
        hits = np.flatnonzero(clear & (logits.argmax(axis=1) == cls))[:per_class]
        if len(hits) < per_class:
            print(f'note: only {len(hits)} synthetic pixels land in class {cls}')
        chosen.extend(hits)
    edge = np.stack([np.zeros(bands), np.ones(bands), np.linspace(0, 1, bands)])
    inputs = np.concatenate([edge, pool[chosen]])
    return inputs, forward(convs, fc, inputs)


def c_float(value):
    text = '%.9g' % np.float32(value)
    if not any(ch in text for ch in '.en'):
        text += '.0'
    return text + 'f'


def c_array(values, indent='    '):
    values = np.asarray(values)
    if values.ndim == 1:
        return '{' + ', '.join(c_float(v) for v in values) + '}'
    inner = (',\n' + indent + ' ').join(c_array(v, indent + ' ') for v in values)
    return '{' + inner + '}'


def write_weights(path, source, convs, fc, k, bands):
    channels = [w.shape[0] for w, _ in convs]
    lines = [
        f'// Generated by tools/export_justoliunet.py from {source}',
        '// Do not edit; re-run the exporter instead.',
        '#ifndef JUSTOLIUNET_WEIGHTS_HPP',
        '#define JUSTOLIUNET_WEIGHTS_HPP',
        '',
        'namespace jl {',
        f'constexpr int BANDS = {bands};',
        f'constexpr int CLASSES = {fc[0].shape[0]};',
        f'constexpr int K = {k};',
        *[f'constexpr int C{i + 1} = {c};' for i, c in enumerate(channels)],
        '',
    ]
    for i, (w, b) in enumerate(convs, start=1):
        lines.append(f'static const float conv{i}_w[C{i}][{"1" if i == 1 else f"C{i - 1}"}][K] = {c_array(w)};')
        lines.append(f'static const float conv{i}_b[C{i}] = {c_array(b)};')
        lines.append('')
    lines.append(f'static const float fc_w[CLASSES][{fc[0].shape[1]}] = {c_array(fc[0])};')
    lines.append(f'static const float fc_b[CLASSES] = {c_array(fc[1])};')
    lines += ['}  // namespace jl', '', '#endif', '']
    path.write_text('\n'.join(lines))


def write_vectors(header, text, source, inputs, expected):
    header.write_text('\n'.join([
        f'// Generated by tools/export_justoliunet.py from {source}',
        '// Inputs and the logits the numpy reference computes for them.',
        '#ifndef JUSTOLIUNET_VECTORS_HPP',
        '#define JUSTOLIUNET_VECTORS_HPP',
        '',
        '#include "justoliunet.hpp"',
        '',
        f'constexpr int JL_VECTORS = {len(inputs)};',
        f'static const float jl_inputs[JL_VECTORS][jl::BANDS] = {c_array(inputs)};',
        f'static const float jl_expected[JL_VECTORS][jl::CLASSES] = {c_array(expected)};',
        '',
        '#endif',
        '',
    ]))
    rows = [f'# Generated by tools/export_justoliunet.py from {source}',
            '# One pixel per line: input bands | expected logits (numpy reference)']
    for x, y in zip(inputs, expected):
        rows.append(' '.join('%.9g' % np.float32(v) for v in x) + ' | '
                    + ' '.join('%.9g' % v for v in y))
    text.write_text('\n'.join(rows) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('checkpoint', nargs='?', default=DEFAULT)
    parser.add_argument('--per-class', type=int, default=4, help='test pixels per predicted class')
    parser.add_argument('--seed', type=int, default=1)
    parser.add_argument('--bands', type=int, help='input bands (default: from the _K<n> in the file name)')
    parser.add_argument('--root', type=Path, default=ROOT, help='repository root to write into')
    args = parser.parse_args()

    checkpoint = Path(args.checkpoint)
    source = checkpoint.resolve().relative_to(ROOT).as_posix() if checkpoint.resolve().is_relative_to(ROOT) \
        else checkpoint.name
    convs, fc = load_layers(checkpoint)
    bands = args.bands or bands_from_name(checkpoint)
    if bands is None:
        raise SystemExit('cannot tell the band count from the file name; pass --bands')
    k = check_sizes(convs, fc, bands)
    inputs, expected = pick_vectors(convs, fc, bands, args.per_class, args.seed)

    kernel_dir = args.root / 'src/hls/justoliunet'
    tb_dir = args.root / 'tb/justoliunet'
    data_dir = args.root / 'tb/data'
    for d in (kernel_dir, tb_dir, data_dir):
        d.mkdir(parents=True, exist_ok=True)
    write_weights(kernel_dir / 'justoliunet_weights.hpp', source, convs, fc, k, bands)
    write_vectors(tb_dir / 'justoliunet_vectors.hpp', data_dir / 'justoliunet_vectors.txt',
                  source, inputs, expected)
    params = sum(w.size + b.size for w, b in convs) + fc[0].size + fc[1].size
    classes = np.bincount(expected.argmax(axis=1), minlength=fc[0].shape[0])
    print(f'{source}: {bands} bands, {params} parameters, '
          f'{len(inputs)} test pixels (per class: {classes.tolist()})')


if __name__ == '__main__':
    main()
