#!/usr/bin/env python3
"""Extract the weights of trained checkpoints for use in HLS kernels (needs numpy, not torch).

For every checkpoint, writes into OUT/<model>/:

  <model>_weights.hpp   every tensor as a `static const float` C++ array, named after
                        its layer (conv1.weight -> conv1_weight) with its real shape
  <model>_weights.npz   the same tensors, for Python (np.load)
  <model>.md            layers, shapes, parameter counts, training scores

and OUT/README.md, a table of all models. Tensors are written exactly as trained:
BatchNorm stays separate (weight, bias, running_mean, running_var, eps 1e-5);
fold it into the preceding convolution in the kernel, or use quantize_weights.py,
which does that. BatchNorm's num_batches_tracked counter is left out.

    python tools/extract_weights.py                       # every .pt under weights/
    python tools/extract_weights.py weights/fp32/sp_unet_small/*.pt
    python tools/extract_weights.py --out some/folder weights/fp32
"""
import argparse
import json
from pathlib import Path
import re

import numpy as np

import pt_reader

ROOT = Path(__file__).resolve().parents[1]
SCORES = ('epoch', 'miou', 'miou_test', 'accuracy_test')


def identifier(name):
    """A C++ identifier from a layer name: double1.block.0.weight -> double1_block_0_weight."""
    text = re.sub(r'\W', '_', name)
    return '_' + text if text[0].isdigit() else text


def c_float(value):
    text = '%.9g' % np.float32(value)  # 9 digits: the exact float32 value
    if not any(ch in text for ch in '.en'):
        text += '.0'
    return text + 'f'


def c_array(values, indent='    '):
    values = np.asarray(values)
    if values.ndim == 1:
        return '{' + ', '.join(c_float(v) for v in values) + '}'
    inner = (',\n' + indent + ' ').join(c_array(v, indent + ' ') for v in values)
    return '{' + inner + '}'


def bands_from_name(path):
    match = re.search(r'_[KC](\d+)(?:_|\.pt$)', Path(path).name)
    return int(match.group(1)) if match else None


def load(path):
    """(model name, metadata, {layer name: float32 array}) from one checkpoint."""
    checkpoint = pt_reader.load(path)
    state = checkpoint.get('state_dict', checkpoint)
    model = checkpoint.get('model') or Path(path).parent.name
    tensors = {name: np.asarray(value, dtype=np.float32) for name, value in state.items()
               if not name.endswith('num_batches_tracked')}
    config = checkpoint.get('config', {})
    meta = {key: checkpoint[key] for key in SCORES if key in checkpoint}
    meta.update({'dataset': checkpoint.get('dataset'), 'classes': config.get('NCLASSES'),
                 'patch_size': config.get('PATCH_SIZE'), 'bands': bands_from_name(path)})
    return str(model), meta, tensors


def write_unix(path, text):
    path.write_bytes(text.encode('utf-8'))


def write_header(path, source, model, meta, tensors):
    space = identifier(model)
    guard = space.upper() + '_WEIGHTS_HPP'
    lines = [f'// Generated by tools/extract_weights.py from {source}',
             f'// {describe(model, meta)}',
             '// Every tensor as trained (float32); BatchNorm is not folded into the convolutions.',
             f'#ifndef {guard}', f'#define {guard}', '', f'namespace {space} {{', '']
    for name, value in tensors.items():
        lines.append(f'// {name}  {list(value.shape)}')
        if value.ndim == 0:
            lines.append(f'static const float {identifier(name)} = {c_float(value)};')
        else:
            dims = ''.join(f'[{d}]' for d in value.shape)
            lines.append(f'static const float {identifier(name)}{dims} = {c_array(value)};')
        lines.append('')
    lines += [f'}}  // namespace {space}', '', '#endif', '']
    write_unix(path, '\n'.join(lines))


def describe(model, meta):
    parts = [f'model {model}']
    for key, label in (('bands', 'bands'), ('classes', 'classes'), ('patch_size', 'patch')):
        if meta.get(key):
            parts.append(f'{label} {meta[key]}')
    if meta.get('miou_test') is not None:
        parts.append(f'test mIoU {meta["miou_test"]:.3f}')
    return ', '.join(parts)


def write_summary(path, source, model, meta, tensors):
    total = sum(v.size for v in tensors.values())
    rows = [f'# {model}', '', f'From `{source}`. {describe(model, meta)}.', '',
            f'Dataset: {meta.get("dataset")}. '
            + ', '.join(f'{key} {meta[key]:.4f}' if isinstance(meta[key], float) else f'{key} {meta[key]}'
                        for key in SCORES if key in meta) + '.',
            '', f'**{total:,} values** (weights, biases, BatchNorm statistics) in {len(tensors)} tensors.', '',
            '| Tensor | C++ name | Shape | Values |', '| --- | --- | --- | --- |']
    rows += [f'| `{name}` | `{identifier(name)}` | {list(v.shape)} | {v.size:,} |' for name, v in tensors.items()]
    write_unix(path, '\n'.join(rows) + '\n')
    return total


def relative(path):
    path = Path(path).resolve()
    return path.relative_to(ROOT).as_posix() if path.is_relative_to(ROOT) else path.as_posix()


def checkpoints(arguments):
    found = []
    for argument in arguments or [ROOT / 'weights']:
        argument = Path(argument)
        found += sorted(argument.rglob('*.pt')) if argument.is_dir() else [argument]
    if not found:
        raise SystemExit('no .pt checkpoints found')
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('checkpoints', nargs='*', help='.pt files or folders (default: weights/)')
    parser.add_argument('--out', type=Path, default=ROOT / 'weights' / 'extracted')
    args = parser.parse_args()

    # The overview keeps every model extracted into this folder, not just this run's.
    index_file = args.out / 'index.json'
    rows = json.loads(index_file.read_text()) if index_file.is_file() else {}
    for path in checkpoints(args.checkpoints):
        model, meta, tensors = load(path)
        source = relative(path)
        folder = args.out / model
        folder.mkdir(parents=True, exist_ok=True)
        write_header(folder / f'{model}_weights.hpp', source, model, meta, tensors)
        np.savez(folder / f'{model}_weights.npz', **tensors)
        total = write_summary(folder / f'{model}.md', source, model, meta, tensors)
        mious = f'{meta["miou_test"]:.3f}' if meta.get('miou_test') is not None else '-'
        rows[model] = (f'| [{model}]({model}/{model}.md) | {total:,} | {meta.get("bands") or "-"} | '
                       f'{meta.get("patch_size") or "-"} | {mious} | `{source}` |')
        print(f'{model:22s} {total:>8,} values  -> {relative(folder)}/')
    rows = {model: row for model, row in sorted(rows.items()) if (args.out / model).is_dir()}
    write_unix(index_file, json.dumps(rows, indent=1) + '\n')
    write_unix(args.out / 'README.md', '\n'.join(
        ['# Extracted weights', '', 'Made by `tools/extract_weights.py`; one folder per model.', '',
         '| Model | Values | Bands | Patch | Test mIoU | Checkpoint |',
         '| --- | --- | --- | --- | --- | --- |', *rows.values()]) + '\n')
    print(f'Overview: {relative(args.out / "README.md")}')


if __name__ == '__main__':
    main()
