#!/usr/bin/env python3
"""Classify a hyperspectral image on the FPGA with justoliunet and check it (numpy).

    1. python tools/justoliunet_image.py prepare CAPTURE-l1a.nc --labels CAPTURE-l1a_labels.npy \\
           --crop 200 300 32 32 --out img
    2. xsdb software/jtag/justoliunet.tcl artifacts/justoliunet/<run> \\
           -pixels img/pixels.txt img/fpga_logits.txt            (board machine)
    3. python tools/justoliunet_image.py compare img

The kernel takes raw L1a spectra and does training's preprocessing itself
(band selection and z-score, see tools/export_justoliunet.py), so the pixels
sent to the board are raw. The image can be:
  - a raw HYPSO-2 capture, CAPTURE-l1a.nc, read as training read it
    (`pip install hypso`); its _labels.npy is remapped as in training;
  - a raw cube .npy, (H, W, 120) or (120, H, W);
  - a prepared training image data<i>.npy (110 bands, already z-scored) with
    label<i>.npy: turned back into raw with the kernel's own statistics.
Classes: 0 cloud, 1 land, 2 sea; other label values count as unlabeled.

compare checks the FPGA logits against a numpy reference of the exact kernel
(same preprocessing constants and checkpoint), scores both against the labels,
and writes PNG maps next to the data. Over JTAG each pixel takes tens of
milliseconds, so use --crop or --step to keep to a few thousand pixels.
"""
import argparse
import json
from pathlib import Path
import re
import struct
import sys
import zlib

import numpy as np

from export_justoliunet import (ROOT, WEIGHTS, check_sizes, forward, load_layers, preprocess,
                                read_preprocessing)

# Label remapping and class order from hypso-onboard-segmentation
# (prepare_hypso_dataset.py remap_labels; train_fp32 reports IoU[Cloud, Land, Sea]).
RAW_LABEL_TO_CLASS = {1: 0, 2: 1, 3: 2, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0}
CLASS_NAMES = ['cloud', 'land', 'sea']
CLASS_COLORS = np.array([[235, 235, 235], [60, 140, 60], [30, 90, 180]], dtype=np.uint8)
NO_DATA = np.array([128, 128, 128], dtype=np.uint8)
DEFAULT_RGB = [56, 67, 86]  # HYPSO-2 r/g/b bands, as in the capture -meta.json files


def built_checkpoint():
    """The checkpoint the kernel's weights header was generated from."""
    match = re.search(r'Generated by tools/export_justoliunet.py from (\S+)', (ROOT / WEIGHTS).read_text())
    if not match:
        raise SystemExit(f'cannot tell which checkpoint {WEIGHTS} came from; pass --checkpoint')
    return ROOT / match.group(1)


def load_capture(path):
    """A raw HYPSO-2 capture's L1a cube, read as prepare_hypso_dataset.py does."""
    try:
        from hypso import Hypso2
    except ImportError:
        raise SystemExit('reading .nc captures needs the hypso package, as in training: pip install hypso')
    return Hypso2(path=Path(path)).l1a_cube.to_numpy().astype(np.float32)


def capture_rgb(nc_path):
    """The capture's own RGB band choice, from the -meta.json beside it."""
    for meta_path in Path(nc_path).parent.glob('*-meta.json'):
        meta = json.loads(meta_path.read_text())
        if all(f'{c}_band' in meta for c in 'rgb'):
            return [int(meta[f'{c}_band']) for c in 'rgb']
    return None


def remap_labels(raw):
    labels = raw.astype(np.int64)
    for value, cls in RAW_LABEL_TO_CLASS.items():
        labels[raw == value] = cls
    return labels


def to_raw(prepared, raw_bands, kept, mean, inv_std):
    """Undo training's preprocessing so the kernel's own preprocessing redoes it."""
    raw = np.zeros(prepared.shape[:2] + (raw_bands,), dtype=np.float32)
    raw[:, :, kept] = prepared / inv_std + mean
    return raw


def load_image(path, raw_bands, kept, mean, inv_std):
    """(cube as raw L1a, kind: 'capture' | 'raw' | 'prepared', default RGB bands)."""
    if str(path).endswith('.nc'):
        cube = load_capture(path)
        print(f'capture: {cube.shape[0]} x {cube.shape[1]} pixels, {cube.shape[2]} bands')
        return cube, 'capture', capture_rgb(path)
    cube = np.load(path)
    if cube.ndim != 3:
        raise SystemExit(f'expected a 3-D cube, got shape {cube.shape}')
    if cube.shape[-1] not in (raw_bands, len(kept)) and cube.shape[0] in (raw_bands, len(kept)):
        cube = cube.transpose(1, 2, 0)
    if cube.shape[-1] == raw_bands:
        return cube.astype(np.float32), 'raw', None
    if cube.shape[-1] == len(kept):
        print(f'{len(kept)} bands: treating this as a prepared, z-scored training image and '
              'converting it back to raw with the kernel\'s statistics')
        return to_raw(cube.astype(np.float32), raw_bands, kept, mean, inv_std), 'prepared', None
    raise SystemExit(f'cube has shape {cube.shape}; expected {raw_bands} raw bands '
                     f'or {len(kept)} prepared bands')


def write_png(path, rgb, scale=1):
    rgb = np.repeat(np.repeat(np.ascontiguousarray(rgb, dtype=np.uint8), scale, 0), scale, 1)
    h, w, _ = rgb.shape
    raw = b''.join(b'\x00' + rgb[y].tobytes() for y in range(h))

    def chunk(tag, data):
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data))

    Path(path).write_bytes(b'\x89PNG\r\n\x1a\n'
                           + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0))
                           + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def display_scale(shape):
    return max(1, 256 // max(shape))


def class_image(classes, known=None):
    rgb = CLASS_COLORS[np.clip(classes, 0, len(CLASS_COLORS) - 1)]
    if known is not None:
        rgb[~known] = NO_DATA
    return rgb


def prepare(args):
    checkpoint = Path(args.checkpoint) if args.checkpoint else built_checkpoint()
    convs, fc = load_layers(checkpoint)
    raw_bands, kept, mean, inv_std, placeholder = read_preprocessing()
    check_sizes(convs, fc, len(kept))

    cube, kind, rgb_default = load_image(args.cube, raw_bands, kept, mean, inv_std)
    labels = None
    if args.labels:
        labels = np.load(args.labels)
        if labels.shape != cube.shape[:2]:
            raise SystemExit(f'labels have shape {labels.shape}, cube is {cube.shape[:2]}')
        if kind == 'capture':
            labels = remap_labels(labels)
            print('labels remapped as in training: '
                  + ', '.join(f'{r}->{c}' for r, c in RAW_LABEL_TO_CLASS.items())
                  + ' (0 cloud, 1 land, 2 sea)')

    row, col, height, width = args.crop or (0, 0, cube.shape[0], cube.shape[1])
    region = (slice(row, row + height, args.step), slice(col, col + width, args.step))
    cube = cube[region]
    if cube.size == 0:
        raise SystemExit('the crop is empty')
    pixels = cube.reshape(-1, raw_bands)
    if not np.isfinite(pixels).all():
        raise SystemExit('the cube contains NaN or infinite values')

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    with open(out / 'pixels.txt', 'w') as f:
        f.write(f'# {len(pixels)} pixels of {args.cube}, row by row, {raw_bands} raw bands each\n')
        for p in pixels:
            f.write(' '.join('%.9g' % v for v in p) + '\n')
    np.save(out / 'reference_logits.npy', forward(convs, fc, preprocess(pixels, kept, mean, inv_std)))
    if labels is not None:
        np.save(out / 'labels.npy', labels[region])
    rgb_bands = args.rgb or rgb_default or DEFAULT_RGB
    rgb = cube[:, :, rgb_bands].astype(np.float64)
    lo, hi = np.percentile(rgb, [2, 98])
    write_png(out / 'rgb.png', np.clip((rgb - lo) / max(hi - lo, 1e-12) * 255, 0, 255),
              display_scale(cube.shape[:2]))
    (out / 'meta.json').write_text(json.dumps({
        'cube': str(args.cube), 'checkpoint': checkpoint.as_posix(), 'shape': list(cube.shape[:2]),
        'crop': [row, col, height, width], 'step': args.step, 'rgb_bands': rgb_bands,
        'meaningful_classes': not placeholder or kind == 'prepared'}, indent=2))

    print(f'{len(pixels)} pixels ({cube.shape[0]} x {cube.shape[1]}) written to {out / "pixels.txt"}')
    if placeholder and kind != 'prepared':
        print('WARNING: the kernel was exported with placeholder normalization, so raw spectra are '
              'not z-scored as in training: FPGA and reference will agree, but the classes will be '
              'wrong. Re-export with --mu-sd and rebuild, or use a prepared data<i>.npy.')
    seconds = len(pixels) * 0.05
    estimate = f'{seconds / 60:.0f} min' if seconds >= 120 else f'{seconds:.0f} s'
    print(f'Over JTAG expect very roughly {estimate}; the board script reports the real rate.')
    print('Next, on the board machine:')
    print(f'  xsdb software/jtag/justoliunet.tcl artifacts/justoliunet/<run> '
          f'-pixels {(out / "pixels.txt").as_posix()} {(out / "fpga_logits.txt").as_posix()}')
    print(f'Then: python tools/justoliunet_image.py compare {out.as_posix()}')


def class_name(c):
    return f'{c} {CLASS_NAMES[c]}' if c < len(CLASS_NAMES) else f'class {c}'


def iou_table(predicted, labels, known, classes):
    rows = []
    for c in range(classes):
        p, t = (predicted == c) & known, (labels == c) & known
        union = (p | t).sum()
        rows.append(float((p & t).sum() / union) if union else float('nan'))
    return rows


def compare(args):
    out = Path(args.dir)
    meta = json.loads((out / 'meta.json').read_text())
    shape = tuple(meta['shape'])
    reference = np.load(out / 'reference_logits.npy')
    rows = [l.split() for l in (out / 'fpga_logits.txt').read_text().splitlines() if l.strip()]
    fpga = np.array(rows, dtype=np.float64).reshape(len(rows), reference.shape[1])
    n, total = len(fpga), len(reference)
    if n < total:
        print(f'warning: fpga_logits.txt has {n} of {total} pixels (interrupted run?); comparing those')
    classes = reference.shape[1]
    ref = reference[:n]

    error = np.abs(fpga - ref)
    close = (error <= 1e-4 + 1e-4 * np.abs(ref)).all(axis=1)
    fpga_cls, ref_cls = fpga.argmax(axis=1), ref.argmax(axis=1)
    agree = fpga_cls == ref_cls
    print(f'{n} pixels compared with the numpy reference of {meta["checkpoint"]}')
    print(f'  logits within tolerance: {close.sum()}/{n}   worst logit error: {error.max():.2e}')
    print(f'  same class:              {agree.sum()}/{n}')
    print('  FPGA class counts:       ' + ', '.join(
        f'{class_name(c)}: {int((fpga_cls == c).sum())}' for c in range(classes)))

    done = np.zeros(total, dtype=bool)
    done[:n] = True
    full_fpga = np.zeros(total, dtype=int)
    full_fpga[:n] = fpga_cls
    scale = display_scale(shape)
    write_png(out / 'fpga_classes.png', class_image(full_fpga, done).reshape(*shape, 3), scale)
    write_png(out / 'reference_classes.png', class_image(reference.argmax(axis=1)).reshape(*shape, 3), scale)
    mismatch = np.full((total, 3), 255, dtype=np.uint8)
    mismatch[:n][~(agree & close)] = [214, 39, 40]
    mismatch[~done] = NO_DATA
    write_png(out / 'mismatch.png', mismatch.reshape(*shape, 3), scale)

    labels_path = out / 'labels.npy'
    if labels_path.exists():
        all_labels = np.load(labels_path).reshape(-1).astype(int)
        all_known = (all_labels >= 0) & (all_labels < classes)
        write_png(out / 'labels.png', class_image(all_labels, all_known).reshape(*shape, 3), scale)
        labels, known = all_labels[:n], all_known[:n]
        if known.any():
            for name, predicted in (('FPGA', fpga_cls), ('reference', ref_cls)):
                acc = (predicted[known] == labels[known]).mean()
                ious = iou_table(predicted, labels, known, classes)
                print(f'  {name:9s} vs labels:     accuracy {acc:.4f}, IoU '
                      + ' '.join(f'{CLASS_NAMES[c] if c < len(CLASS_NAMES) else c} {v:.3f}'
                                 for c, v in enumerate(ious))
                      + f', mIoU {np.nanmean(ious):.3f} ({int(known.sum())} labeled pixels)')
    if not meta.get('meaningful_classes', True):
        print('  (placeholder normalization on raw input: the scores against labels are not meaningful)')

    print(f'Maps in {out.as_posix()}/: rgb, fpga_classes, reference_classes, mismatch (red = differs from reference)'
          + (', labels' if labels_path.exists() else '')
          + '. Colors: cloud white, land green, sea blue; gray = no data.')
    ok = close.all() and agree.all() and n == total
    print('MATCH: the FPGA reproduces the reference on every pixel' if ok else 'MISMATCH: see above')
    return 0 if ok else 1


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)
    p = sub.add_parser('prepare', help='image -> raw pixels for the board + reference results')
    p.add_argument('cube', help='CAPTURE-l1a.nc, a raw .npy cube, or a prepared data<i>.npy')
    p.add_argument('--labels', help='(H, W) .npy: the capture\'s _labels.npy, or label<i>.npy')
    p.add_argument('--out', required=True, help='directory for this image')
    p.add_argument('--crop', type=int, nargs=4, metavar=('ROW', 'COL', 'HEIGHT', 'WIDTH'))
    p.add_argument('--step', type=int, default=1, help='use every STEP-th row and column')
    p.add_argument('--checkpoint', help='default: the one the kernel weights were exported from')
    p.add_argument('--rgb', type=int, nargs=3, metavar=('R', 'G', 'B'), help='raw band indices for rgb.png')
    c = sub.add_parser('compare', help='FPGA logits vs reference and labels, plus PNG maps')
    c.add_argument('dir')
    args = parser.parse_args()
    if args.command == 'prepare':
        if args.step < 1:
            raise SystemExit('--step must be at least 1')
        prepare(args)
        return 0
    return compare(args)


if __name__ == '__main__':
    sys.exit(main())
